# Generated by Django 5.1.1 on 2025-05-27 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('content', models.TextField(verbose_name='сообщение')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d', verbose_name='картинка')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.news', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
