# Generated by Django 5.1.1 on 2024-09-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название группы')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя студента')),
                ('surname', models.CharField(max_length=30, verbose_name='фамилия студента')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('pair_number', models.PositiveIntegerField(verbose_name='номер пары')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent_excused', 'Отсутствовал с уважительной причиной'), ('absent_unexcused', 'Отсутствовал без уважительной причины'), ('unknown', 'Неизвестно')], max_length=20)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='pass_log.student', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'посещаемости',
                'verbose_name_plural': 'посещаемости',
                'unique_together': {('student', 'date', 'pair_number')},
            },
        ),
    ]
