# Generated by Django 5.1.1 on 2025-04-03 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_log', '0002_student_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='captain',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_groups', to=settings.AUTH_USER_MODEL, verbose_name='староста'),
        ),
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_groups', to=settings.AUTH_USER_MODEL, verbose_name='куратор'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствовал'), ('absent_excused', 'Отсутствовал с уважительной причиной'), ('absent_unexcused', 'Отсутствовал без уважительной причины'), ('unknown', 'Неизвестно')], max_length=20, verbose_name='причина пропуска'),
        ),
    ]
