# Generated by Django 5.1.1 on 2025-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_log', '0003_group_captain_group_curator_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('absent', 'Отсутствовал')], max_length=20, verbose_name='причина пропуска'),
        ),
    ]
